### ISSUE TITLE
このプロジェクトでまずやること

### ISSUE THREAD

**Issue by harperfu6** [harperfu6/ExperimentMyOneDollar#1]
## 概要
このIssueは、ExperimentMyOneDollarのタスク一覧です．
とりあえず独自のOneDollarであるofxMyOneDollarのアルゴリズムを作る．
その後そのアルゴリズムを用いて，認識率を測定できる実験アプリケーションを作る．
 
#### 規約
のちにアドオン化・SDKしやすいように
ofApp.cppにはアルゴリズムを含めない(ofxMyOneDollar.h及びそのディレクトリで完結させる)

#### Todo
- [ ] それぞれのジェスチャを複数登録できる
- [ ] 特徴量によるアルゴリズムの計算の実装
- [ ] ストロークの分割による認識率の向上の実装

#### 規約
基本的には，つまみやボタンのUIと結果を表示する文字Viewのみで良いが，
テンプレートを手動で選ぶときには，テンプレートが描画Viewされると分かりやすいかも

#### Todo
- [ ] ストロークデータをxmlからインポートする
- [ ] ストロークデータの大きさ，形状，向き，位置を手動で変形できる(これにより，それぞれの特徴量がどれだけ変化すると識別できるかをテストしやすい)
- [ ] テンプレートと入力データをランダムに選んで認識のテストをする(これにより，少ない(と言ってもある程度の)数で，大量の実験ができる)
- [ ] 手動で選ぶとき，テンプレートが描画される
- [ ] テンプレートと入力データを手動で選んで認識のテストをする(これにより，テンプレートデータに何を使うか選定できる)
- [ ] ストロークデータをスマートフォンからリアルタイムにインポートする
